# Generated by Django 4.1.5 on 2023-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='STAFF_ID',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
