# Generated by Django 4.1.5 on 2023-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0004_remove_order_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='Unset Name', max_length=20),
        ),
    ]
