# Generated by Django 4.1.5 on 2023-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0005_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparing',
            field=models.BooleanField(default=True),
        ),
    ]
