# Generated by Django 4.1.5 on 2023-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0006_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('appetizers', 'Appetizers'), ('entrees', 'Entrees'), ('tacos', 'Tacos'), ('burritos', 'Burritos'), ('quesadillas', 'Quesadillas'), ('sides', 'Sides'), ('drinks', 'Drinks')], default='Entrees', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='menu/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
