# Generated by Django 4.1.5 on 2023-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0007_menuitems_delete_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.CharField(choices=[('appetisers', 'Appetisers'), ('entrees', 'Entrees'), ('tacos', 'Tacos'), ('burritos', 'Burritos'), ('quesadillas', 'Quesadillas'), ('sides', 'Sides'), ('drinks', 'Drinks')], default='Entrees', max_length=20),
        ),
    ]
