# Generated by Django 4.1.5 on 2023-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0008_alter_menuitems_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='menuitems',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='ingredients',
            field=models.TextField(default=''),
        ),
    ]
