# Generated by Django 4.1.5 on 2023-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0010_menucategory_alter_menuitems_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.CharField(choices=[('appetisers', 'Appetisers'), ('entrees', 'Entrees'), ('tacos', 'Tacos'), ('burritos', 'Burritos'), ('quesadillas', 'Quesadillas'), ('sides', 'Sides'), ('drinks', 'Drinks')], default='Entrees', max_length=20),
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
