# Generated by Django 4.1.5 on 2023-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0013_alter_menucategory_options_alter_menuitems_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
