# Generated by Django 4.1.5 on 2023-02-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0016_remove_order_id_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('iname', models.CharField(max_length=150)),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='ManagerApp.item')),
            ],
        ),
    ]
