# Generated by Django 4.1.5 on 2023-02-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0006_order_preparing'),
        ('ManagerApp', '0017_item'),
    ]

    operations = [
    ]
