# Generated by Django 4.1.5 on 2023-02-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0018_merge_0006_order_preparing_0017_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='ManagerApp.order'),
        ),
    ]
