# Generated by Django 4.1.5 on 2023-03-09 18:47

import ManagerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0024_alter_item_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='id',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='item_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[ManagerApp.models.validate_image_size]),
        ),
    ]
