# Generated by Django 4.1.5 on 2023-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0025_remove_item_order_remove_menuitems_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
