# Generated by Django 4.1.5 on 2023-03-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0026_alter_menuitems_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
