# Generated by Django 4.1.5 on 2023-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ManagerApp", "0030_alter_menuitems_calories_alter_table_table_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cardholder_name", models.CharField(max_length=255)),
                ("card_number", models.CharField(max_length=19)),
                ("expiry_date", models.DateField()),
                ("cvv", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
